packages:
  - packages/vscode-ai-gateway
  - packages/openresponses-client
  - configs/tsconfig

catalog:
  "@ai-sdk/gateway": 3.0.23
  "@ai-sdk/openai": 3.0.18
  "@ai-sdk/provider": 3.0.5
  "@ai-sdk/provider-utils": 4.0.9
  "@kubb/cli": 4.18.5
  "@kubb/core": 4.18.5
  "@kubb/plugin-oas": 4.18.5
  "@kubb/plugin-ts": 4.18.5
  "@kubb/plugin-zod": 4.18.5
  "@types/json-schema": 7.0.15
  "@types/node": 25.0.10
  "@vscode/vsce": 3.7.1
  ai: 6.0.50
  fast-check: ^3.23.2
  knip: 5.82.1
  tsx: 4.21.0
  typescript: 5.9.3
  vitest: 4.0.18
  zod: 4.3.6
