import {
	activeCallbacksActiveCallbacksGet,
	activeCallbacksSettingsGet,
	addAllowedIpAddAllowedIpPost,
	addMcpServerV1McpServerPost,
	addMessagesThreadsThreadIdMessagesPost,
	addMessagesV1ThreadsThreadIdMessagesPost,
	addNewModelModelNewPost,
	addTeamCallbacksTeamTeamIdCallbackPost,
	anthropicResponseV1MessagesPost,
	applyGuardrailApplyGuardrailPost,
	applyGuardrailGuardrailsApplyGuardrailPost,
	audioSpeechAudioSpeechPost,
	audioSpeechV1AudioSpeechPost,
	audioTranscriptionsAudioTranscriptionsPost,
	audioTranscriptionsV1AudioTranscriptionsPost,
	authorizeAuthorizeGet,
	authorizeMcpServerNameAuthorizeGet,
	availableEnterpriseUsersUserAvailableUsersGet,
	blockKeyKeyBlockPost,
	blockTeamTeamBlockPost,
	blockUserCustomerBlockPost,
	budgetSettingsBudgetSettingsGet,
	bulkTeamMemberAddTeamBulkMemberAddPost,
	bulkUserUpdateUserBulkUpdatePost,
	cacheDeleteCacheDeletePost,
	cacheFlushallCacheFlushallPost,
	cachePingCachePingGet,
	cacheRedisInfoCacheRedisInfoGet,
	calculateSpendSpendCalculatePost,
	callbackCallbackGet,
	callToolRestApiMcpRestToolsCallPost,
	cancelBatchBatchesBatchIdCancelPost,
	cancelBatchProviderV1BatchesBatchIdCancelPost,
	cancelBatchV1BatchesBatchIdCancelPost,
	cancelFineTuningJobFineTuningJobsFineTuningJobIdCancelPost,
	cancelFineTuningJobV1FineTuningJobsFineTuningJobIdCancelPost,
	cancelResponseOpenaiV1ResponsesResponseIdCancelPost,
	cancelResponseResponsesResponseIdCancelPost,
	cancelResponseV1ResponsesResponseIdCancelPost,
	chatCompletionChatCompletionsPost,
	chatCompletionEnginesModelChatCompletionsPost,
	chatCompletionOpenaiDeploymentsModelChatCompletionsPost,
	chatCompletionV1ChatCompletionsPost,
	cloudzeroDryRunExportCloudzeroDryRunPost,
	cloudzeroExportCloudzeroExportPost,
	completionCompletionsPost,
	completionEnginesModelCompletionsPost,
	completionOpenaiDeploymentsModelCompletionsPost,
	completionV1CompletionsPost,
	convertPromptFileToJsonUtilsDotpromptJsonConverterPost,
	countTokensV1MessagesCountTokensPost,
	createAssistantAssistantsPost,
	createAssistantV1AssistantsPost,
	createBatchBatchesPost,
	createBatchProviderV1BatchesPost,
	createBatchV1BatchesPost,
	createContainerContainersPost,
	createContainerV1ContainersPost,
	createCredentialCredentialsPost,
	createFileFilesPost,
	createFileProviderV1FilesPost,
	createFileV1FilesPost,
	createFineTuningJobFineTuningJobsPost,
	createFineTuningJobV1FineTuningJobsPost,
	createGroupScimV2GroupsPost,
	createGuardrailGuardrailsPost,
	createPassThroughEndpointsConfigPassThroughEndpointPost,
	createPromptPromptsPost,
	createSearchToolSearchToolsPost,
	createThreadsThreadsPost,
	createThreadsV1ThreadsPost,
	createUserScimV2UsersPost,
	deleteAllowedIpDeleteAllowedIpPost,
	deleteAssistantAssistantsAssistantIdDelete,
	deleteAssistantV1AssistantsAssistantIdDelete,
	deleteBudgetBudgetDeletePost,
	deleteContainerContainersContainerIdDelete,
	deleteContainerV1ContainersContainerIdDelete,
	deleteCredentialCredentialsCredentialNameDelete,
	deleteEndUserCustomerDeletePost,
	deleteFileFilesFileIdDelete,
	deleteFileProviderV1FilesFileIdDelete,
	deleteFileV1FilesFileIdDelete,
	deleteGroupScimV2GroupsGroupIdDelete,
	deleteGuardrailGuardrailsGuardrailIdDelete,
	deleteKeyFnKeyDeletePost,
	deleteModelModelDeletePost,
	deleteOrganizationOrganizationDeleteDelete,
	deletePassThroughEndpointsConfigPassThroughEndpointDelete,
	deletePromptPromptsPromptIdDelete,
	deleteResponseOpenaiV1ResponsesResponseIdDelete,
	deleteResponseResponsesResponseIdDelete,
	deleteResponseV1ResponsesResponseIdDelete,
	deleteSearchToolSearchToolsSearchToolIdDelete,
	deleteTagTagDeletePost,
	deleteTeamTeamDeletePost,
	deleteUserScimV2UsersUserIdDelete,
	deleteUserUserDeletePost,
	deleteVectorStoreVectorStoreDeletePost,
	deprecatedInfoOrganizationOrganizationInfoPost,
	disableTeamLoggingTeamTeamIdDisableLoggingPost,
	dynamicMcpRouteMcpServerNameMcpPatch,
	dynamicMcpRouteMcpServerNameMcpPatch2,
	dynamicMcpRouteMcpServerNameMcpPatch3,
	dynamicMcpRouteMcpServerNameMcpPatch4,
	dynamicMcpRouteMcpServerNameMcpPatch5,
	editMcpServerV1McpServerPut,
	embeddingsEmbeddingsPost,
	embeddingsEnginesModelEmbeddingsPost,
	embeddingsOpenaiDeploymentsModelEmbeddingsPost,
	embeddingsV1EmbeddingsPost,
	endUserInfoCustomerInfoGet,
	fetchAllMcpServersV1McpServerGet,
	fetchMcpServerV1McpServerServerIdGet,
	generateKeyFnKeyGeneratePost,
	generateServiceAccountKeyFnKeyServiceAccountGeneratePost,
	getActiveTasksStatsDebugAsyncioTasksGet,
	getAssistantsAssistantsGet,
	getAssistantsV1AssistantsGet,
	getAuditLogByIdAuditIdGet,
	getAuditLogsAuditGet,
	getAvailableSearchProvidersSearchToolsUiAvailableProvidersGet,
	getCacheSettingsCacheSettingsGet,
	getCloudzeroSettingsCloudzeroSettingsGet,
	getCostDiscountConfigConfigCostDiscountConfigGet,
	getCredentialCredentialsByModelModelIdGet,
	getCredentialCredentialsByNameCredentialNameGet,
	getCredentialsCredentialsGet,
	getDailyActiveUsersTagDauGet,
	getDefaultTeamSettingsGetDefaultTeamSettingsGet,
	getDistinctUserAgentTagsTagDistinctGet,
	getEmailEventSettingsEmailEventSettingsGet,
	getFileContentFilesFileIdContentGet,
	getFileContentProviderV1FilesFileIdContentGet,
	getFileContentV1FilesFileIdContentGet,
	getFileFilesFileIdGet,
	getFileProviderV1FilesFileIdGet,
	getFileV1FilesFileIdGet,
	getGlobalSpendReportGlobalSpendReportGet,
	getGroupScimV2GroupsGroupIdGet,
	getGroupsScimV2GroupsGet,
	getGuardrailInfoGuardrailsGuardrailIdGet,
	getGuardrailInfoGuardrailsGuardrailIdInfoGet,
	getGuardrailUiSettingsGuardrailsUiAddGuardrailSettingsGet,
	getInternalUserSettingsGetInternalUserSettingsGet,
	getMcpAccessGroupsV1McpAccessGroupsGet,
	getMcpToolsV1McpToolsGet,
	getMessagesThreadsThreadIdMessagesGet,
	getMessagesV1ThreadsThreadIdMessagesGet,
	getMonthlyActiveUsersTagMauGet,
	getPassThroughEndpointsConfigPassThroughEndpointGet,
	getPassThroughEndpointsConfigPassThroughEndpointTeamTeamIdGet,
	getPerUserAnalyticsTagUserAgentPerUserAnalyticsGet,
	getPromptInfoPromptsPromptIdGet,
	getPromptInfoPromptsPromptIdInfoGet,
	getProviderSpecificParamsGuardrailsUiProviderSpecificParamsGet,
	getResponseInputItemsOpenaiV1ResponsesResponseIdInputItemsGet,
	getResponseInputItemsResponsesResponseIdInputItemsGet,
	getResponseInputItemsV1ResponsesResponseIdInputItemsGet,
	getResponseOpenaiV1ResponsesResponseIdGet,
	getResponseResponsesResponseIdGet,
	getResponseV1ResponsesResponseIdGet,
	getRobotsRobotsTxtGet,
	getRouterSettingsRouterSettingsGet,
	getRoutesRoutesGet,
	getSearchToolInfoSearchToolsSearchToolIdGet,
	getServiceProviderConfigScimV2ServiceProviderConfigGet,
	getSsoSettingsGetSsoSettingsGet,
	getTagDailyActivityTagDailyActivityGet,
	getTagSummaryTagSummaryGet,
	getTeamCallbacksTeamTeamIdCallbackGet,
	getTeamDailyActivityTeamDailyActivityGet,
	getThreadThreadsThreadIdGet,
	getThreadV1ThreadsThreadIdGet,
	getUiConfigLitellmWellKnownLitellmUiConfigGet,
	getUiConfigWellKnownLitellmUiConfigGet,
	getUiThemeSettingsGetUiThemeSettingsGet,
	getUserDailyActivityAggregatedUserDailyActivityAggregatedGet,
	getUserDailyActivityUserDailyActivityGet,
	getUserScimV2UsersUserIdGet,
	getUsersScimV2UsersGet,
	getUsersUserListGet,
	getVectorStoreInfoVectorStoreInfoPost,
	getWeeklyActiveUsersTagWauGet,
	globalSpendResetGlobalSpendResetPost,
	globalViewSpendTagsGlobalSpendTagsGet,
	googleCountTokensModelsModelNameCountTokensPost,
	googleCountTokensV1betaModelsModelNameCountTokensPost,
	googleGenerateContentModelsModelNameGenerateContentPost,
	googleGenerateContentV1betaModelsModelNameGenerateContentPost,
	googleStreamGenerateContentModelsModelNameStreamGenerateContentPost,
	googleStreamGenerateContentV1betaModelsModelNameStreamGenerateContentPost,
	healthCheckAllMcpServersV1McpServerHealthGet,
	healthCheckHistoryEndpointHealthHistoryGet,
	healthCheckMcpServerV1McpServerServerIdHealthGet,
	healthEndpointHealthGet,
	healthLivelinessHealthLivelinessGet,
	healthLivelinessHealthLivenessGet,
	healthReadinessHealthReadinessGet,
	healthServicesEndpointHealthServicesGet,
	homeGet,
	imageEditApiImagesEditsPost,
	imageEditApiOpenaiDeploymentsModelImagesEditsPost,
	imageEditApiV1ImagesEditsPost,
	imageGenerationImagesGenerationsPost,
	imageGenerationOpenaiDeploymentsModelImagesGenerationsPost,
	imageGenerationV1ImagesGenerationsPost,
	indexCreateV1IndexesPost,
	infoBudgetBudgetInfoPost,
	infoKeyFnKeyInfoGet,
	infoOrganizationOrganizationInfoGet,
	infoTagTagInfoPost,
	initCloudzeroSettingsCloudzeroInitPost,
	keyAliasesKeyAliasesGet,
	keyHealthKeyHealthPost,
	latestHealthChecksEndpointHealthLatestGet,
	listAvailableTeamsTeamAvailableGet,
	listBatchesBatchesGet,
	listBatchesProviderV1BatchesGet,
	listBatchesV1BatchesGet,
	listBudgetBudgetListGet,
	listCallbacksCallbacksListGet,
	listContainersContainersGet,
	listContainersV1ContainersGet,
	listEndUserCustomerListGet,
	listFilesFilesGet,
	listFilesProviderV1FilesGet,
	listFilesV1FilesGet,
	listFineTuningJobsFineTuningJobsGet,
	listFineTuningJobsV1FineTuningJobsGet,
	listGuardrailsGuardrailsListGet,
	listGuardrailsV2V2GuardrailsListGet,
	listKeysKeyListGet,
	listOrganizationOrganizationListGet,
	listPromptsPromptsListGet,
	listSearchToolsSearchToolsListGet,
	listTagsTagListGet,
	listTeamTeamListGet,
	listTeamV2V2TeamListGet,
	listToolRestApiMcpRestToolsListGet,
	listVectorStoresVectorStoreListGet,
	modelGroupInfoModelGroupInfoGet,
	modelInfoModelsModelIdGet,
	modelInfoV1ModelInfoGet,
	modelInfoV1ModelsModelIdGet,
	modelInfoV1V1ModelInfoGet,
	modelListModelsGet,
	modelListV1ModelsGet,
	moderationsModerationsPost,
	moderationsV1ModerationsPost,
	newBudgetBudgetNewPost,
	newEndUserCustomerNewPost,
	newOrganizationOrganizationNewPost,
	newTagTagNewPost,
	newTeamTeamNewPost,
	newUserUserNewPost,
	newVectorStoreVectorStoreNewPost,
	oauthAuthorizationServerMcpWellKnownOauthAuthorizationServerMcpServerNameGet,
	oauthAuthorizationServerRootWellKnownOauthAuthorizationServerGet,
	oauthAuthorizationServerRootWellKnownOauthAuthorizationServerMcpServerNameMcpGet,
	oauthProtectedResourceMcpWellKnownOauthProtectedResourceGet,
	oauthProtectedResourceMcpWellKnownOauthProtectedResourceMcpServerNameMcpGet,
	ocrOcrPost,
	ocrV1OcrPost,
	openidConfigurationWellKnownOpenidConfigurationGet,
	organizationMemberAddOrganizationMemberAddPost,
	organizationMemberDeleteOrganizationMemberDeleteDelete,
	organizationMemberUpdateOrganizationMemberUpdatePatch,
	patchGroupScimV2GroupsGroupIdPatch,
	patchGuardrailGuardrailsGuardrailIdPatch,
	patchModelModelModelIdUpdatePatch,
	patchPromptPromptsPromptIdPatch,
	patchUserScimV2UsersUserIdPatch,
	providerBudgetsProviderBudgetsGet,
	publicModelHubInfoPublicModelHubInfoGet,
	publicModelHubPublicModelHubGet,
	regenerateKeyFnKeyKeyRegeneratePost,
	regenerateKeyFnKeyRegeneratePost,
	registerClientMcpServerNameRegisterPost,
	registerClientRegisterPost,
	removeMcpServerV1McpServerServerIdDelete,
	rerankRerankPost,
	rerankV1RerankPost,
	rerankV2RerankPost,
	resetEventSettingsEmailEventSettingsResetPost,
	responsesApiOpenaiV1ResponsesPost,
	responsesApiResponsesPost,
	responsesApiV1ResponsesPost,
	retrieveBatchBatchesBatchIdGet,
	retrieveBatchProviderV1BatchesBatchIdGet,
	retrieveBatchV1BatchesBatchIdGet,
	retrieveContainerContainersContainerIdGet,
	retrieveContainerV1ContainersContainerIdGet,
	retrieveFineTuningJobFineTuningJobsFineTuningJobIdGet,
	retrieveFineTuningJobV1FineTuningJobsFineTuningJobIdGet,
	runThreadThreadsThreadIdRunsPost,
	runThreadV1ThreadsThreadIdRunsPost,
	searchSearchPost,
	searchSearchSearchToolNamePost,
	searchV1SearchPost,
	searchV1SearchSearchToolNamePost,
	sharedHealthCheckStatusEndpointHealthSharedStatusGet,
	supportedOpenaiParamsUtilsSupportedOpenaiParamsGet,
	teamInfoTeamInfoGet,
	teamMemberAddTeamMemberAddPost,
	teamMemberDeleteTeamMemberDeletePost,
	teamMemberPermissionsTeamPermissionsListGet,
	teamMemberUpdateTeamMemberUpdatePost,
	teamModelAddTeamModelAddPost,
	teamModelDeleteTeamModelDeletePost,
	testCacheConnectionCacheSettingsTestPost,
	testConnectionMcpRestTestConnectionPost,
	testEndpointTestGet,
	testModelConnectionHealthTestConnectionPost,
	testSearchToolConnectionSearchToolsTestConnectionPost,
	testToolsListMcpRestTestToolsListPost,
	tokenCounterUtilsTokenCounterPost,
	tokenEndpointMcpServerNameTokenPost,
	tokenEndpointTokenPost,
	transformRequestUtilsTransformRequestPost,
	unblockKeyKeyUnblockPost,
	unblockTeamTeamUnblockPost,
	unblockUserCustomerUnblockPost,
	updateBudgetBudgetUpdatePost,
	updateCacheSettingsCacheSettingsPost,
	updateCloudzeroSettingsCloudzeroSettingsPut,
	updateCostDiscountConfigConfigCostDiscountConfigPatch,
	updateCredentialCredentialsCredentialNamePatch,
	updateDefaultTeamSettingsUpdateDefaultTeamSettingsPatch,
	updateEndUserCustomerUpdatePost,
	updateEventSettingsEmailEventSettingsPatch,
	updateGroupScimV2GroupsGroupIdPut,
	updateGuardrailGuardrailsGuardrailIdPut,
	updateInternalUserSettingsUpdateInternalUserSettingsPatch,
	updateKeyFnKeyUpdatePost,
	updateModelModelUpdatePost,
	updateOrganizationOrganizationUpdatePatch,
	updatePassThroughEndpointsConfigPassThroughEndpointEndpointIdPost,
	updatePromptPromptsPromptIdPut,
	updatePublicModelGroupsModelGroupMakePublicPost,
	updateSearchToolSearchToolsSearchToolIdPut,
	updateSsoSettingsUpdateSsoSettingsPatch,
	updateTagTagUpdatePost,
	updateTeamMemberPermissionsTeamPermissionsUpdatePost,
	updateTeamTeamUpdatePost,
	updateUiThemeSettingsUpdateUiThemeSettingsPatch,
	updateUsefulLinksModelHubUpdateUsefulLinksPost,
	updateUserScimV2UsersUserIdPut,
	updateVectorStoreVectorStoreUpdatePost,
	uploadLogoUploadLogoPost,
	userInfoUserInfoGet,
	userUpdateUserUpdatePost,
	validateBlockedWordsFileGuardrailsValidateBlockedWordsFilePost,
	vectorStoreCreateV1VectorStoresPost,
	vectorStoreCreateVectorStoresPost,
	vectorStoreSearchV1VectorStoresVectorStoreIdSearchPost,
	vectorStoreSearchVectorStoresVectorStoreIdSearchPost,
	videoContentV1VideosVideoIdContentGet,
	videoContentVideosVideoIdContentGet,
	videoGenerationV1VideosPost,
	videoGenerationVideosPost,
	videoListV1VideosGet,
	videoListVideosGet,
	videoRemixV1VideosVideoIdRemixPost,
	videoRemixVideosVideoIdRemixPost,
	videoStatusV1VideosVideoIdGet,
	videoStatusVideosVideoIdGet,
	viewSpendLogsSpendLogsGet,
	viewSpendTagsSpendTagsGet,
	websocketVertexAiLivePassthroughEndpoint,
	websocketWebsocketEndpoint,
	websocketWebsocketEndpoint2,
} from "./components";

export const operationsByPath = {
	"GET /models": modelListModelsGet,
	"GET /v1/models": modelListV1ModelsGet,
	"GET /models/{model_id}": modelInfoModelsModelIdGet,
	"GET /v1/models/{model_id}": modelInfoV1ModelsModelIdGet,
	"POST /openai/deployments/{model}/chat/completions":
		chatCompletionOpenaiDeploymentsModelChatCompletionsPost,
	"POST /engines/{model}/chat/completions": chatCompletionEnginesModelChatCompletionsPost,
	"POST /chat/completions": chatCompletionChatCompletionsPost,
	"POST /v1/chat/completions": chatCompletionV1ChatCompletionsPost,
	"POST /openai/deployments/{model}/completions": completionOpenaiDeploymentsModelCompletionsPost,
	"POST /engines/{model}/completions": completionEnginesModelCompletionsPost,
	"POST /completions": completionCompletionsPost,
	"POST /v1/completions": completionV1CompletionsPost,
	"POST /openai/deployments/{model}/embeddings": embeddingsOpenaiDeploymentsModelEmbeddingsPost,
	"POST /engines/{model}/embeddings": embeddingsEnginesModelEmbeddingsPost,
	"POST /embeddings": embeddingsEmbeddingsPost,
	"POST /v1/embeddings": embeddingsV1EmbeddingsPost,
	"POST /moderations": moderationsModerationsPost,
	"POST /v1/moderations": moderationsV1ModerationsPost,
	"POST /audio/speech": audioSpeechAudioSpeechPost,
	"POST /v1/audio/speech": audioSpeechV1AudioSpeechPost,
	"POST /audio/transcriptions": audioTranscriptionsAudioTranscriptionsPost,
	"POST /v1/audio/transcriptions": audioTranscriptionsV1AudioTranscriptionsPost,
	"GET /assistants": getAssistantsAssistantsGet,
	"POST /assistants": createAssistantAssistantsPost,
	"GET /v1/assistants": getAssistantsV1AssistantsGet,
	"POST /v1/assistants": createAssistantV1AssistantsPost,
	"DELETE /assistants/{assistant_id}": deleteAssistantAssistantsAssistantIdDelete,
	"DELETE /v1/assistants/{assistant_id}": deleteAssistantV1AssistantsAssistantIdDelete,
	"POST /threads": createThreadsThreadsPost,
	"POST /v1/threads": createThreadsV1ThreadsPost,
	"GET /threads/{thread_id}": getThreadThreadsThreadIdGet,
	"GET /v1/threads/{thread_id}": getThreadV1ThreadsThreadIdGet,
	"POST /threads/{thread_id}/messages": addMessagesThreadsThreadIdMessagesPost,
	"GET /threads/{thread_id}/messages": getMessagesThreadsThreadIdMessagesGet,
	"POST /v1/threads/{thread_id}/messages": addMessagesV1ThreadsThreadIdMessagesPost,
	"GET /v1/threads/{thread_id}/messages": getMessagesV1ThreadsThreadIdMessagesGet,
	"POST /threads/{thread_id}/runs": runThreadThreadsThreadIdRunsPost,
	"POST /v1/threads/{thread_id}/runs": runThreadV1ThreadsThreadIdRunsPost,
	"POST /utils/token_counter": tokenCounterUtilsTokenCounterPost,
	"GET /utils/supported_openai_params": supportedOpenaiParamsUtilsSupportedOpenaiParamsGet,
	"POST /utils/transform_request": transformRequestUtilsTransformRequestPost,
	"GET /v1/model/info": modelInfoV1V1ModelInfoGet,
	"GET /model/info": modelInfoV1ModelInfoGet,
	"GET /model_group/info": modelGroupInfoModelGroupInfoGet,
	"GET /": homeGet,
	"GET /routes": getRoutesRoutesGet,
	"POST /openai/v1/responses": responsesApiOpenaiV1ResponsesPost,
	"POST /responses": responsesApiResponsesPost,
	"POST /v1/responses": responsesApiV1ResponsesPost,
	"GET /openai/v1/responses/{response_id}": getResponseOpenaiV1ResponsesResponseIdGet,
	"DELETE /openai/v1/responses/{response_id}": deleteResponseOpenaiV1ResponsesResponseIdDelete,
	"GET /responses/{response_id}": getResponseResponsesResponseIdGet,
	"DELETE /responses/{response_id}": deleteResponseResponsesResponseIdDelete,
	"GET /v1/responses/{response_id}": getResponseV1ResponsesResponseIdGet,
	"DELETE /v1/responses/{response_id}": deleteResponseV1ResponsesResponseIdDelete,
	"GET /openai/v1/responses/{response_id}/input_items":
		getResponseInputItemsOpenaiV1ResponsesResponseIdInputItemsGet,
	"GET /responses/{response_id}/input_items": getResponseInputItemsResponsesResponseIdInputItemsGet,
	"GET /v1/responses/{response_id}/input_items":
		getResponseInputItemsV1ResponsesResponseIdInputItemsGet,
	"POST /openai/v1/responses/{response_id}/cancel":
		cancelResponseOpenaiV1ResponsesResponseIdCancelPost,
	"POST /responses/{response_id}/cancel": cancelResponseResponsesResponseIdCancelPost,
	"POST /v1/responses/{response_id}/cancel": cancelResponseV1ResponsesResponseIdCancelPost,
	"POST /batches": createBatchBatchesPost,
	"GET /batches": listBatchesBatchesGet,
	"POST /v1/batches": createBatchV1BatchesPost,
	"GET /v1/batches": listBatchesV1BatchesGet,
	"POST /{provider}/v1/batches": createBatchProviderV1BatchesPost,
	"GET /{provider}/v1/batches": listBatchesProviderV1BatchesGet,
	"GET /batches/{batch_id}": retrieveBatchBatchesBatchIdGet,
	"GET /v1/batches/{batch_id}": retrieveBatchV1BatchesBatchIdGet,
	"GET /{provider}/v1/batches/{batch_id}": retrieveBatchProviderV1BatchesBatchIdGet,
	"POST /batches/{batch_id}/cancel": cancelBatchBatchesBatchIdCancelPost,
	"POST /v1/batches/{batch_id}/cancel": cancelBatchV1BatchesBatchIdCancelPost,
	"POST /{provider}/v1/batches/{batch_id}/cancel": cancelBatchProviderV1BatchesBatchIdCancelPost,
	"GET /public/model_hub": publicModelHubPublicModelHubGet,
	"GET /public/model_hub/info": publicModelHubInfoPublicModelHubInfoGet,
	"POST /rerank": rerankRerankPost,
	"POST /v1/rerank": rerankV1RerankPost,
	"POST /v2/rerank": rerankV2RerankPost,
	"POST /ocr": ocrOcrPost,
	"POST /v1/ocr": ocrV1OcrPost,
	"GET /videos": videoListVideosGet,
	"POST /videos": videoGenerationVideosPost,
	"GET /v1/videos": videoListV1VideosGet,
	"POST /v1/videos": videoGenerationV1VideosPost,
	"GET /videos/{video_id}": videoStatusVideosVideoIdGet,
	"GET /v1/videos/{video_id}": videoStatusV1VideosVideoIdGet,
	"GET /videos/{video_id}/content": videoContentVideosVideoIdContentGet,
	"GET /v1/videos/{video_id}/content": videoContentV1VideosVideoIdContentGet,
	"POST /videos/{video_id}/remix": videoRemixVideosVideoIdRemixPost,
	"POST /v1/videos/{video_id}/remix": videoRemixV1VideosVideoIdRemixPost,
	"GET /containers": listContainersContainersGet,
	"POST /containers": createContainerContainersPost,
	"GET /v1/containers": listContainersV1ContainersGet,
	"POST /v1/containers": createContainerV1ContainersPost,
	"GET /containers/{container_id}": retrieveContainerContainersContainerIdGet,
	"DELETE /containers/{container_id}": deleteContainerContainersContainerIdDelete,
	"GET /v1/containers/{container_id}": retrieveContainerV1ContainersContainerIdGet,
	"DELETE /v1/containers/{container_id}": deleteContainerV1ContainersContainerIdDelete,
	"POST /search": searchSearchPost,
	"POST /v1/search": searchV1SearchPost,
	"POST /search/{search_tool_name}": searchSearchSearchToolNamePost,
	"POST /v1/search/{search_tool_name}": searchV1SearchSearchToolNamePost,
	"POST /openai/deployments/{model}/images/generations":
		imageGenerationOpenaiDeploymentsModelImagesGenerationsPost,
	"POST /images/generations": imageGenerationImagesGenerationsPost,
	"POST /v1/images/generations": imageGenerationV1ImagesGenerationsPost,
	"POST /openai/deployments/{model}/images/edits":
		imageEditApiOpenaiDeploymentsModelImagesEditsPost,
	"POST /images/edits": imageEditApiImagesEditsPost,
	"POST /v1/images/edits": imageEditApiV1ImagesEditsPost,
	"POST /fine_tuning/jobs": createFineTuningJobFineTuningJobsPost,
	"GET /fine_tuning/jobs": listFineTuningJobsFineTuningJobsGet,
	"POST /v1/fine_tuning/jobs": createFineTuningJobV1FineTuningJobsPost,
	"GET /v1/fine_tuning/jobs": listFineTuningJobsV1FineTuningJobsGet,
	"GET /fine_tuning/jobs/{fine_tuning_job_id}":
		retrieveFineTuningJobFineTuningJobsFineTuningJobIdGet,
	"GET /v1/fine_tuning/jobs/{fine_tuning_job_id}":
		retrieveFineTuningJobV1FineTuningJobsFineTuningJobIdGet,
	"POST /fine_tuning/jobs/{fine_tuning_job_id}/cancel":
		cancelFineTuningJobFineTuningJobsFineTuningJobIdCancelPost,
	"POST /v1/fine_tuning/jobs/{fine_tuning_job_id}/cancel":
		cancelFineTuningJobV1FineTuningJobsFineTuningJobIdCancelPost,
	"POST /vector_stores/{vector_store_id}/search":
		vectorStoreSearchVectorStoresVectorStoreIdSearchPost,
	"POST /v1/vector_stores/{vector_store_id}/search":
		vectorStoreSearchV1VectorStoresVectorStoreIdSearchPost,
	"POST /vector_stores": vectorStoreCreateVectorStoresPost,
	"POST /v1/vector_stores": vectorStoreCreateV1VectorStoresPost,
	"POST /v1/indexes": indexCreateV1IndexesPost,
	"GET /credentials": getCredentialsCredentialsGet,
	"POST /credentials": createCredentialCredentialsPost,
	"GET /credentials/by_model/{model_id}": getCredentialCredentialsByModelModelIdGet,
	"GET /credentials/by_name/{credential_name}": getCredentialCredentialsByNameCredentialNameGet,
	"DELETE /credentials/{credential_name}": deleteCredentialCredentialsCredentialNameDelete,
	"PATCH /credentials/{credential_name}": updateCredentialCredentialsCredentialNamePatch,
	"GET /v1/mcp/tools": getMcpToolsV1McpToolsGet,
	"GET /v1/mcp/access_groups": getMcpAccessGroupsV1McpAccessGroupsGet,
	"GET /v1/mcp/server/{server_id}/health": healthCheckMcpServerV1McpServerServerIdHealthGet,
	"GET /v1/mcp/server/health": healthCheckAllMcpServersV1McpServerHealthGet,
	"GET /v1/mcp/server": fetchAllMcpServersV1McpServerGet,
	"POST /v1/mcp/server": addMcpServerV1McpServerPost,
	"PUT /v1/mcp/server": editMcpServerV1McpServerPut,
	"GET /v1/mcp/server/{server_id}": fetchMcpServerV1McpServerServerIdGet,
	"DELETE /v1/mcp/server/{server_id}": removeMcpServerV1McpServerServerIdDelete,
	"POST /v1/messages": anthropicResponseV1MessagesPost,
	"POST /v1/messages/count_tokens": countTokensV1MessagesCountTokensPost,
	"POST /models/{model_name}:generateContent":
		googleGenerateContentModelsModelNameGenerateContentPost,
	"POST /v1beta/models/{model_name}:generateContent":
		googleGenerateContentV1betaModelsModelNameGenerateContentPost,
	"POST /models/{model_name}:streamGenerateContent":
		googleStreamGenerateContentModelsModelNameStreamGenerateContentPost,
	"POST /v1beta/models/{model_name}:streamGenerateContent":
		googleStreamGenerateContentV1betaModelsModelNameStreamGenerateContentPost,
	"POST /models/{model_name}:countTokens": googleCountTokensModelsModelNameCountTokensPost,
	"POST /v1beta/models/{model_name}:countTokens":
		googleCountTokensV1betaModelsModelNameCountTokensPost,
	"GET /config/pass_through_endpoint/team/{team_id}":
		getPassThroughEndpointsConfigPassThroughEndpointTeamTeamIdGet,
	"GET /config/pass_through_endpoint": getPassThroughEndpointsConfigPassThroughEndpointGet,
	"POST /config/pass_through_endpoint": createPassThroughEndpointsConfigPassThroughEndpointPost,
	"DELETE /config/pass_through_endpoint": deletePassThroughEndpointsConfigPassThroughEndpointDelete,
	"POST /config/pass_through_endpoint/{endpoint_id}":
		updatePassThroughEndpointsConfigPassThroughEndpointEndpointIdPost,
	"GET /test": testEndpointTestGet,
	"GET /health/services": healthServicesEndpointHealthServicesGet,
	"GET /health": healthEndpointHealthGet,
	"GET /health/history": healthCheckHistoryEndpointHealthHistoryGet,
	"GET /health/latest": latestHealthChecksEndpointHealthLatestGet,
	"GET /health/shared-status": sharedHealthCheckStatusEndpointHealthSharedStatusGet,
	"GET /active/callbacks": activeCallbacksActiveCallbacksGet,
	"GET /settings": activeCallbacksSettingsGet,
	"GET /health/readiness": healthReadinessHealthReadinessGet,
	"GET /health/liveness": healthLivelinessHealthLivenessGet,
	"GET /health/liveliness": healthLivelinessHealthLivelinessGet,
	"POST /health/test_connection": testModelConnectionHealthTestConnectionPost,
	"POST /key/generate": generateKeyFnKeyGeneratePost,
	"POST /key/service-account/generate": generateServiceAccountKeyFnKeyServiceAccountGeneratePost,
	"POST /key/update": updateKeyFnKeyUpdatePost,
	"POST /key/delete": deleteKeyFnKeyDeletePost,
	"GET /key/info": infoKeyFnKeyInfoGet,
	"POST /key/regenerate": regenerateKeyFnKeyRegeneratePost,
	"POST /key/{key}/regenerate": regenerateKeyFnKeyKeyRegeneratePost,
	"GET /key/list": listKeysKeyListGet,
	"GET /key/aliases": keyAliasesKeyAliasesGet,
	"POST /key/block": blockKeyKeyBlockPost,
	"POST /key/unblock": unblockKeyKeyUnblockPost,
	"POST /key/health": keyHealthKeyHealthPost,
	"POST /user/new": newUserUserNewPost,
	"GET /user/info": userInfoUserInfoGet,
	"POST /user/update": userUpdateUserUpdatePost,
	"POST /user/bulk_update": bulkUserUpdateUserBulkUpdatePost,
	"GET /user/list": getUsersUserListGet,
	"POST /user/delete": deleteUserUserDeletePost,
	"GET /user/daily/activity": getUserDailyActivityUserDailyActivityGet,
	"GET /user/daily/activity/aggregated":
		getUserDailyActivityAggregatedUserDailyActivityAggregatedGet,
	"POST /team/new": newTeamTeamNewPost,
	"POST /team/update": updateTeamTeamUpdatePost,
	"POST /team/member_add": teamMemberAddTeamMemberAddPost,
	"POST /team/member_delete": teamMemberDeleteTeamMemberDeletePost,
	"POST /team/member_update": teamMemberUpdateTeamMemberUpdatePost,
	"POST /team/bulk_member_add": bulkTeamMemberAddTeamBulkMemberAddPost,
	"POST /team/delete": deleteTeamTeamDeletePost,
	"GET /team/info": teamInfoTeamInfoGet,
	"POST /team/block": blockTeamTeamBlockPost,
	"POST /team/unblock": unblockTeamTeamUnblockPost,
	"GET /team/available": listAvailableTeamsTeamAvailableGet,
	"GET /v2/team/list": listTeamV2V2TeamListGet,
	"GET /team/list": listTeamTeamListGet,
	"POST /team/model/add": teamModelAddTeamModelAddPost,
	"POST /team/model/delete": teamModelDeleteTeamModelDeletePost,
	"GET /team/permissions_list": teamMemberPermissionsTeamPermissionsListGet,
	"POST /team/permissions_update": updateTeamMemberPermissionsTeamPermissionsUpdatePost,
	"GET /team/daily/activity": getTeamDailyActivityTeamDailyActivityGet,
	"GET /scim/v2/ServiceProviderConfig": getServiceProviderConfigScimV2ServiceProviderConfigGet,
	"GET /scim/v2/Users": getUsersScimV2UsersGet,
	"POST /scim/v2/Users": createUserScimV2UsersPost,
	"GET /scim/v2/Users/{user_id}": getUserScimV2UsersUserIdGet,
	"PUT /scim/v2/Users/{user_id}": updateUserScimV2UsersUserIdPut,
	"DELETE /scim/v2/Users/{user_id}": deleteUserScimV2UsersUserIdDelete,
	"PATCH /scim/v2/Users/{user_id}": patchUserScimV2UsersUserIdPatch,
	"GET /scim/v2/Groups": getGroupsScimV2GroupsGet,
	"POST /scim/v2/Groups": createGroupScimV2GroupsPost,
	"GET /scim/v2/Groups/{group_id}": getGroupScimV2GroupsGroupIdGet,
	"PUT /scim/v2/Groups/{group_id}": updateGroupScimV2GroupsGroupIdPut,
	"DELETE /scim/v2/Groups/{group_id}": deleteGroupScimV2GroupsGroupIdDelete,
	"PATCH /scim/v2/Groups/{group_id}": patchGroupScimV2GroupsGroupIdPatch,
	"POST /organization/new": newOrganizationOrganizationNewPost,
	"PATCH /organization/update": updateOrganizationOrganizationUpdatePatch,
	"DELETE /organization/delete": deleteOrganizationOrganizationDeleteDelete,
	"GET /organization/list": listOrganizationOrganizationListGet,
	"GET /organization/info": infoOrganizationOrganizationInfoGet,
	"POST /organization/info": deprecatedInfoOrganizationOrganizationInfoPost,
	"POST /organization/member_add": organizationMemberAddOrganizationMemberAddPost,
	"PATCH /organization/member_update": organizationMemberUpdateOrganizationMemberUpdatePatch,
	"DELETE /organization/member_delete": organizationMemberDeleteOrganizationMemberDeleteDelete,
	"POST /customer/block": blockUserCustomerBlockPost,
	"POST /customer/unblock": unblockUserCustomerUnblockPost,
	"POST /customer/new": newEndUserCustomerNewPost,
	"GET /customer/info": endUserInfoCustomerInfoGet,
	"POST /customer/update": updateEndUserCustomerUpdatePost,
	"POST /customer/delete": deleteEndUserCustomerDeletePost,
	"GET /customer/list": listEndUserCustomerListGet,
	"GET /spend/tags": viewSpendTagsSpendTagsGet,
	"GET /global/spend/report": getGlobalSpendReportGlobalSpendReportGet,
	"GET /global/spend/tags": globalViewSpendTagsGlobalSpendTagsGet,
	"POST /spend/calculate": calculateSpendSpendCalculatePost,
	"GET /spend/logs": viewSpendLogsSpendLogsGet,
	"POST /global/spend/reset": globalSpendResetGlobalSpendResetPost,
	"GET /provider/budgets": providerBudgetsProviderBudgetsGet,
	"GET /cloudzero/settings": getCloudzeroSettingsCloudzeroSettingsGet,
	"PUT /cloudzero/settings": updateCloudzeroSettingsCloudzeroSettingsPut,
	"POST /cloudzero/init": initCloudzeroSettingsCloudzeroInitPost,
	"POST /cloudzero/dry-run": cloudzeroDryRunExportCloudzeroDryRunPost,
	"POST /cloudzero/export": cloudzeroExportCloudzeroExportPost,
	"GET /cache/ping": cachePingCachePingGet,
	"POST /cache/delete": cacheDeleteCacheDeletePost,
	"GET /cache/redis/info": cacheRedisInfoCacheRedisInfoGet,
	"POST /cache/flushall": cacheFlushallCacheFlushallPost,
	"GET /guardrails/list": listGuardrailsGuardrailsListGet,
	"GET /v2/guardrails/list": listGuardrailsV2V2GuardrailsListGet,
	"POST /guardrails": createGuardrailGuardrailsPost,
	"PUT /guardrails/{guardrail_id}": updateGuardrailGuardrailsGuardrailIdPut,
	"DELETE /guardrails/{guardrail_id}": deleteGuardrailGuardrailsGuardrailIdDelete,
	"PATCH /guardrails/{guardrail_id}": patchGuardrailGuardrailsGuardrailIdPatch,
	"GET /guardrails/{guardrail_id}": getGuardrailInfoGuardrailsGuardrailIdGet,
	"GET /guardrails/{guardrail_id}/info": getGuardrailInfoGuardrailsGuardrailIdInfoGet,
	"GET /guardrails/ui/add_guardrail_settings":
		getGuardrailUiSettingsGuardrailsUiAddGuardrailSettingsGet,
	"POST /guardrails/validate_blocked_words_file":
		validateBlockedWordsFileGuardrailsValidateBlockedWordsFilePost,
	"GET /guardrails/ui/provider_specific_params":
		getProviderSpecificParamsGuardrailsUiProviderSpecificParamsGet,
	"POST /apply_guardrail": applyGuardrailApplyGuardrailPost,
	"POST /guardrails/apply_guardrail": applyGuardrailGuardrailsApplyGuardrailPost,
	"GET /search_tools/list": listSearchToolsSearchToolsListGet,
	"POST /search_tools": createSearchToolSearchToolsPost,
	"PUT /search_tools/{search_tool_id}": updateSearchToolSearchToolsSearchToolIdPut,
	"DELETE /search_tools/{search_tool_id}": deleteSearchToolSearchToolsSearchToolIdDelete,
	"GET /search_tools/{search_tool_id}": getSearchToolInfoSearchToolsSearchToolIdGet,
	"POST /search_tools/test_connection": testSearchToolConnectionSearchToolsTestConnectionPost,
	"GET /search_tools/ui/available_providers":
		getAvailableSearchProvidersSearchToolsUiAvailableProvidersGet,
	"GET /prompts/list": listPromptsPromptsListGet,
	"GET /prompts/{prompt_id}/info": getPromptInfoPromptsPromptIdInfoGet,
	"GET /prompts/{prompt_id}": getPromptInfoPromptsPromptIdGet,
	"PUT /prompts/{prompt_id}": updatePromptPromptsPromptIdPut,
	"DELETE /prompts/{prompt_id}": deletePromptPromptsPromptIdDelete,
	"PATCH /prompts/{prompt_id}": patchPromptPromptsPromptIdPatch,
	"POST /prompts": createPromptPromptsPost,
	"POST /utils/dotprompt_json_converter": convertPromptFileToJsonUtilsDotpromptJsonConverterPost,
	"GET /callbacks/list": listCallbacksCallbacksListGet,
	"GET /debug/asyncio-tasks": getActiveTasksStatsDebugAsyncioTasksGet,
	"POST /add/allowed_ip": addAllowedIpAddAllowedIpPost,
	"POST /delete/allowed_ip": deleteAllowedIpDeleteAllowedIpPost,
	"GET /get/internal_user_settings": getInternalUserSettingsGetInternalUserSettingsGet,
	"GET /get/default_team_settings": getDefaultTeamSettingsGetDefaultTeamSettingsGet,
	"PATCH /update/internal_user_settings": updateInternalUserSettingsUpdateInternalUserSettingsPatch,
	"PATCH /update/default_team_settings": updateDefaultTeamSettingsUpdateDefaultTeamSettingsPatch,
	"GET /get/sso_settings": getSsoSettingsGetSsoSettingsGet,
	"PATCH /update/sso_settings": updateSsoSettingsUpdateSsoSettingsPatch,
	"GET /get/ui_theme_settings": getUiThemeSettingsGetUiThemeSettingsGet,
	"PATCH /update/ui_theme_settings": updateUiThemeSettingsUpdateUiThemeSettingsPatch,
	"POST /upload/logo": uploadLogoUploadLogoPost,
	"POST /files": createFileFilesPost,
	"GET /files": listFilesFilesGet,
	"POST /v1/files": createFileV1FilesPost,
	"GET /v1/files": listFilesV1FilesGet,
	"POST /{provider}/v1/files": createFileProviderV1FilesPost,
	"GET /{provider}/v1/files": listFilesProviderV1FilesGet,
	"GET /files/{file_id}/content": getFileContentFilesFileIdContentGet,
	"GET /v1/files/{file_id}/content": getFileContentV1FilesFileIdContentGet,
	"GET /{provider}/v1/files/{file_id}/content": getFileContentProviderV1FilesFileIdContentGet,
	"GET /files/{file_id}": getFileFilesFileIdGet,
	"DELETE /files/{file_id}": deleteFileFilesFileIdDelete,
	"GET /v1/files/{file_id}": getFileV1FilesFileIdGet,
	"DELETE /v1/files/{file_id}": deleteFileV1FilesFileIdDelete,
	"GET /{provider}/v1/files/{file_id}": getFileProviderV1FilesFileIdGet,
	"DELETE /{provider}/v1/files/{file_id}": deleteFileProviderV1FilesFileIdDelete,
	"POST /team/{team_id}/callback": addTeamCallbacksTeamTeamIdCallbackPost,
	"GET /team/{team_id}/callback": getTeamCallbacksTeamTeamIdCallbackGet,
	"POST /team/{team_id}/disable_logging": disableTeamLoggingTeamTeamIdDisableLoggingPost,
	"POST /budget/new": newBudgetBudgetNewPost,
	"POST /budget/update": updateBudgetBudgetUpdatePost,
	"POST /budget/info": infoBudgetBudgetInfoPost,
	"GET /budget/settings": budgetSettingsBudgetSettingsGet,
	"GET /budget/list": listBudgetBudgetListGet,
	"POST /budget/delete": deleteBudgetBudgetDeletePost,
	"PATCH /model/{model_id}/update": patchModelModelModelIdUpdatePatch,
	"POST /model/delete": deleteModelModelDeletePost,
	"POST /model/new": addNewModelModelNewPost,
	"POST /model/update": updateModelModelUpdatePost,
	"POST /model_group/make_public": updatePublicModelGroupsModelGroupMakePublicPost,
	"POST /model_hub/update_useful_links": updateUsefulLinksModelHubUpdateUsefulLinksPost,
	"POST /tag/new": newTagTagNewPost,
	"POST /tag/update": updateTagTagUpdatePost,
	"POST /tag/info": infoTagTagInfoPost,
	"GET /tag/list": listTagsTagListGet,
	"POST /tag/delete": deleteTagTagDeletePost,
	"GET /tag/daily/activity": getTagDailyActivityTagDailyActivityGet,
	"GET /config/cost_discount_config": getCostDiscountConfigConfigCostDiscountConfigGet,
	"PATCH /config/cost_discount_config": updateCostDiscountConfigConfigCostDiscountConfigPatch,
	"GET /router/settings": getRouterSettingsRouterSettingsGet,
	"GET /cache/settings": getCacheSettingsCacheSettingsGet,
	"POST /cache/settings": updateCacheSettingsCacheSettingsPost,
	"POST /cache/settings/test": testCacheConnectionCacheSettingsTestPost,
	"GET /tag/distinct": getDistinctUserAgentTagsTagDistinctGet,
	"GET /tag/dau": getDailyActiveUsersTagDauGet,
	"GET /tag/wau": getWeeklyActiveUsersTagWauGet,
	"GET /tag/mau": getMonthlyActiveUsersTagMauGet,
	"GET /tag/summary": getTagSummaryTagSummaryGet,
	"GET /tag/user-agent/per-user-analytics": getPerUserAnalyticsTagUserAgentPerUserAnalyticsGet,
	"POST /vector_store/new": newVectorStoreVectorStoreNewPost,
	"GET /vector_store/list": listVectorStoresVectorStoreListGet,
	"POST /vector_store/delete": deleteVectorStoreVectorStoreDeletePost,
	"POST /vector_store/info": getVectorStoreInfoVectorStoreInfoPost,
	"POST /vector_store/update": updateVectorStoreVectorStoreUpdatePost,
	"GET /email/event_settings": getEmailEventSettingsEmailEventSettingsGet,
	"PATCH /email/event_settings": updateEventSettingsEmailEventSettingsPatch,
	"POST /email/event_settings/reset": resetEventSettingsEmailEventSettingsResetPost,
	"GET /audit": getAuditLogsAuditGet,
	"GET /audit/{id}": getAuditLogByIdAuditIdGet,
	"GET /user/available_users": availableEnterpriseUsersUserAvailableUsersGet,
	"GET /robots.txt": getRobotsRobotsTxtGet,
	"GET /litellm/.well-known/litellm-ui-config": getUiConfigLitellmWellKnownLitellmUiConfigGet,
	"GET /.well-known/litellm-ui-config": getUiConfigWellKnownLitellmUiConfigGet,
	"PATCH /{mcp_server_name}/mcp": dynamicMcpRouteMcpServerNameMcpPatch4,
	"POST /{mcp_server_name}/mcp": dynamicMcpRouteMcpServerNameMcpPatch2,
	"PUT /{mcp_server_name}/mcp": dynamicMcpRouteMcpServerNameMcpPatch3,
	"GET /{mcp_server_name}/mcp": dynamicMcpRouteMcpServerNameMcpPatch,
	"DELETE /{mcp_server_name}/mcp": dynamicMcpRouteMcpServerNameMcpPatch5,
	"GET /mcp-rest/tools/list": listToolRestApiMcpRestToolsListGet,
	"POST /mcp-rest/tools/call": callToolRestApiMcpRestToolsCallPost,
	"POST /mcp-rest/test/connection": testConnectionMcpRestTestConnectionPost,
	"POST /mcp-rest/test/tools/list": testToolsListMcpRestTestToolsListPost,
	"GET /authorize": authorizeAuthorizeGet,
	"GET /{mcp_server_name}/authorize": authorizeMcpServerNameAuthorizeGet,
	"POST /token": tokenEndpointTokenPost,
	"POST /{mcp_server_name}/token": tokenEndpointMcpServerNameTokenPost,
	"GET /callback": callbackCallbackGet,
	"GET /.well-known/oauth-protected-resource":
		oauthProtectedResourceMcpWellKnownOauthProtectedResourceGet,
	"GET /.well-known/oauth-protected-resource/{mcp_server_name}/mcp":
		oauthProtectedResourceMcpWellKnownOauthProtectedResourceMcpServerNameMcpGet,
	"GET /.well-known/oauth-authorization-server":
		oauthAuthorizationServerRootWellKnownOauthAuthorizationServerGet,
	"GET /.well-known/oauth-authorization-server/{mcp_server_name}":
		oauthAuthorizationServerMcpWellKnownOauthAuthorizationServerMcpServerNameGet,
	"GET /.well-known/openid-configuration": openidConfigurationWellKnownOpenidConfigurationGet,
	"GET /.well-known/oauth-authorization-server/{mcp_server_name}/mcp":
		oauthAuthorizationServerRootWellKnownOauthAuthorizationServerMcpServerNameMcpGet,
	"POST /register": registerClientRegisterPost,
	"POST /{mcp_server_name}/register": registerClientMcpServerNameRegisterPost,
	"GET /vertex_ai/live": websocketVertexAiLivePassthroughEndpoint,
	"GET /realtime": websocketWebsocketEndpoint,
	"GET /v1/realtime": websocketWebsocketEndpoint2,
};
